id = "sagemath"
name = "SageMath"
version = "0.0.1"
schema_version = 1
authors = ["Mathias Hall-Andersen <mathias@hall-andersen.dk>"]
description = "SageMath Support for Zed"
repository = "https://github.com/rot256/zed-sagemath"

[grammars.sage]
repository = "https://github.com/havarddj/tree-sitter-sage.git"
commit = "de002c5abf9e14bf92a643b4af9057d0ceb612a5"
